Add eventing-github to repo config for sandbox
knative/community pull request #261
Opened 2020-09-03 14:16 UTC by lionelvillard

For https://github.com/knative/community/issues/223

2020-09-03 14:17 UTC, lionelvillard commented
/assign @evankanderson

2020-09-09 07:16 UTC, pierDipi requested changes

2020-09-09 07:16 UTC, pierDipi commented on peribolos/knative-sandbox.yaml
> -          eventing-kafka-broker: admin
Why?

2020-09-09 07:16 UTC, slinkydeveloper commented on peribolos/knative-sandbox.yaml
> -          eventing-kafka-broker: admin
waaaat @lionelvillard ?

2020-09-09 07:16 UTC, slinkydeveloper commented
/hold

2020-09-09 12:25 UTC, lionelvillard commented on peribolos/knative-sandbox.yaml
> -          eventing-kafka-broker: admin
oops. Fixed. Thanks for catching this!

2020-09-09 12:26 UTC, lionelvillard commented
/unhold

I fixed it.

2020-09-10 18:42 UTC, evankanderson commented
/lgtm
/approve

Things seem to be alphabetical, the names match the tickets, and all the names are in all the places.

2020-09-10 18:45 UTC, merged