Add groups based on observed usage in knative repos
knative/community pull request #552
Opened 2021-03-31 23:40 UTC by evankanderson

(PRs incoming shortly for each repo to use the groups defined here.)

Note that I did not preserve _all_ groups that existing in each OWNERS_ALIASES file. I also needed to create several groups, and split up `Serving Writers` into Working Group based groups.

My criteria for creating groups in peribolos was:
1. Associated with an existing WG (e.g. "$FOO Reviewers" for those working to approver for a WG)
2. **Multiple** directories which should have consistent ownership. There were a number of cases where a group was defined in OWNER_ALIASES and then used in only a single OWNERS file, which seems to simply make extra work. I inlined these groups in the per-repo PRs.

Note that I did _not_ try to rationalize much of the existing files, simply to migrate them to OWNERS_ALIASES

Another change which hasn't yet been done is adding in the "release leads" rotation. I expect to do that during this week, but since Markus and I have TOC approvers in most repos, I don't expect this to be a speedbump for 0.22

2021-03-31 23:43 UTC, evankanderson commented
/verify-owners

2021-03-31 23:49 UTC, evankanderson commented
/retest

2021-04-01 23:12 UTC, evankanderson commented
/assign @vaikas 

(For `/approve` of root-level OWNERS_ALIASES)

2021-04-06 17:15 UTC, dprotaso requested changes

2021-04-06 17:15 UTC, dprotaso commented on peribolos/knative.yaml
> +            - grantr
can you add me here?

2021-04-06 17:16 UTC, dprotaso commented on peribolos/knative.yaml
> +            description: Approvers for configmap utilities in pkg
typo 
```suggestion
            description: Approvers for controller utilities in pkg
```

2021-04-06 23:46 UTC, evankanderson commented on peribolos/knative.yaml
> +            - grantr
Done.

2021-04-06 23:46 UTC, evankanderson commented on peribolos/knative.yaml
> +            description: Approvers for configmap utilities in pkg
Fixed.

2021-04-07 21:11 UTC, vaikas approved these changes
/lgtm

/hold
just adding a hold in case others want to chime in. Remove as y'all see fit.

2021-04-08 10:42 UTC, rhuss commented
/lgtm , too

2021-04-08 16:44 UTC, evankanderson commented
/hold cancel

2021-04-08 16:53 UTC, merged